### PR TITLE
Backfill

### PR DESCRIPTION
**Pull request by crissian**

### CODE REVIEW

**Comment by Rayman2200** [comment]
There is one minor problem with the calculation. The calculation does not take account of the workforce. So if the productivity rise and more wares are produced, there are less modules needed as the calculator return. 

For example 3 Antimatter Cell Productions with 1 Argon L Habitat and 930 Worker, Should only need 1 Energycell Production.

**Comment by crissian** [comment]
I'm not sure I follow. If I calculate with your specific example, if you have a workforce, more energy cells are produced.

As an example, calculate with 5 Antimatter Cell Production and 1 Energy Cell Production - with and without workforce.

**Comment by Rayman2200** [comment]
[calculation.mkv.zip](https://github.com/crissian/x4/files/4557664/calculation.mkv.zip)

A video is worth a thousand words :)

**Comment by leinardi** [comment]
This is incredibly useful! Thanks!

**Comment by crissian** [comment]
> [calculation.mkv.zip](https://github.com/crissian/x4/files/4557664/calculation.mkv.zip)
> 
> A video is worth a thousand words :)

Thanks, I see the issue now. What browser are you using in the video?

**Comment by Rayman2200** [comment]
Google Chrome 80

**Comment by crissian** [comment]
ok I see, it's a resolution issue. The autofill button should be on the same line as add module button. I'll also fix that.

**Pull request merged**
